build: Fix build for macOS due to C++17 extension
MediaElch still supports C++14.  But a recent commit uses a C++17
feature, which made the macOS build fail.  The error message was:

```
19:30:54  /Users/jenkins/MediaElch/macOS Qt5/src/scrapers/movie/omdb/OmdbMovieSearchJob.cpp:85:16: error: decomposition declarations are a C++17 extension [-Werror,-Wc++17-extensions]
19:30:54      const auto [query, year] = extractYear(config().query);
19:30:54                 ^~~~~~~~~~~~~
19:30:54  1 error generated.
```